#!/bin/bash
#SBATCH --account=swang585_1200
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=90G
#SBATCH --time=48:00:00

module load conda
conda activate cellSNP

cellsnp-lite -s /project/swang585_1200/cellSNP/cellSNP_GM12878_10x/possorted_genome_bam.bam -b /project/swang585_1200/cellSNP/cellSNP_GM12878_10x/barcodes.tsv -O /project/swang585_1200/cellSNP$

conda deactivate
