#!/bin/bash
#SBATCH --account=swang585_1200
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --time=3:00:00

cp #the file you want to be copied (specify the full directory)# #the new directory you want to copy it to#
