#!/bin/bash

#SBATCH --account=swang585_1200
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --time=30:00:00

module load sratoolkit
fastq-dump --gzip --split-files -A SRR8427168
